---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true

- name: Install HAProxy
  ansible.builtin.apt:
    name: haproxy
    state: present

- name: Install Keepalived and dependencies
  ansible.builtin.apt:
    name: 
    - policycoreutils-python-utils
    - keepalived 
    state: present

- name: Copy HAProxy configuration file to master node
  ansible.builtin.template:
    src: "master.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    group: "root"
    owner: "root"
    mode: "0644"
    backup: true
  notify: Restart haproxy
  when: "'loadbalancer' in group_names and groups['loadbalancer']|length == 1 and inventory_hostname == groups['loadbalancer'][0]"

- name: Copy HAProxy configuration file to backup node
  ansible.builtin.template:
    src: "backup.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    group: "root"
    owner: "root"
    mode: "0644"
    backup: true
  notify: Restart haproxy
  when: "'loadbalancer' in group_names and groups['loadbalancer']|length == 2 and inventory_hostname == groups['loadbalancer'][1]"