- name: Generate master join command in master-01
  ansible.builtin.shell: |
    #!/bin/bash
    set -o pipefail
    echo "$(kubeadm token create --print-join-command) --control-plane --certificate-key $(kubeadm init phase upload-certs --upload-certs 2>/dev/null | grep -vw -e certificate -e Namespace) --apiserver-advertise-address={{ hostvars[groups['master'][1]]['ansible_host'] }}"
  args:
    executable: /bin/bash
  register: master_join_command
  become: true
  become_user: root
  changed_when: true
  when: (groups['master'] | default([]) | length > 1) and inventory_hostname == groups['master'][0]

- name: Save master join command to template file from master-01
  ansible.builtin.copy:
    content: "{{ master_join_command.stdout }}"
    dest: master.join.j2
    mode: 0644
  when: (groups['master'] | default([]) | length > 1) and inventory_hostname == groups['master'][0]

- name: Fetch master.join.j2 to local machine from master-01
  ansible.builtin.fetch:
    src: master.join.j2
    dest: roles/join_masters/templates/masters.join.j2
    flat: yes
  when: (groups['master'] | default([]) | length > 1) and inventory_hostname == groups['master'][0]

- name: Transfer  master join command to master-02
  ansible.builtin.template:
    src: masters.join.j2
    dest: /home/{{ ansible_user }}/master.join.sh
    mode: "0755"
  when: "(groups['master'] | default([]) | length > 1) and ansible_hostname == groups['master'][1]"

- name: Execute master join command to master-02
  ansible.builtin.shell: |
    #!/bin/bash
    set -o pipefail
    /home/{{ ansible_user }}/master.join.sh
  args:
    executable: /bin/bash
  register: command_output
  changed_when: false
  become: true
  when: "(groups['master'] | default([]) | length > 1) and ansible_hostname == groups['master'][1]"